name: dp-timzatko

channels:
  - anaconda
  - conda-forge

dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - SimpleITK
  - scikit-image
  - tqdm
  - pillow
  - opencv
  - ipywidgets
  - scipy
  - jupyter
  - libtiff
  - libxml2
  - libxslt
  - lxml
  - pytorch
  - torchvision
  - cudatoolkit=10.1
  - pytorch
  - pip
  - pip:
    - tensorflow==2.3.1
    - tensorboard==2.4.0
    - opencv-python
    - seaborn
    - ipyparams
    - innvestigate
    - intel-openmp
